/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author USER
 */
import Backend.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class FormMobil extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public FormMobil() {
        initComponents();
        tampilkanData();
        tampilkanCmbJenis();
        kosongkanForm();
        tampilkanCmbView();
    }

    public void kosongkanForm() {
        txtidmobil.setText("0");
        txtnopol.setText("");
        txtmerk.setText("");
        txtwarna.setText("");
        txtnama.setText("");
    }

    public void tampilkanCmbJenis() {
        cmbJenis.setModel(new DefaultComboBoxModel(new JenisMobil().getAll().toArray()));
    }

    public void tampilkanCmbView() {
        DefaultComboBoxModel mdl = new DefaultComboBoxModel();
        cmbView.setModel(mdl);
        mdl.addElement("View All");
        mdl.addElement("Mobil Keluarga");
        mdl.addElement("Mobil PickUp");

    }

    public void tampilkanData() {
        String[] kolom = {"ID Mobil", "Jenis", "No Polisi", "Merk", "Warna", "Nama", "Harga Sewa / Hr"};
        ArrayList<MobilKeluarga> list = new MobilKeluarga().getAll();
        ArrayList<MobilPickUp> listp = new MobilPickUp().getAll();
        Object rowData[] = new Object[7];

        table.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdMobil();
            rowData[1] = list.get(i).getJenis().getJenis();
            rowData[2] = list.get(i).getNopol();
            rowData[3] = list.get(i).getMerkMobil();
            rowData[4] = list.get(i).getWarnaMobil();
            rowData[5] = list.get(i).getNamaMobil();
            rowData[6] = list.get(i).getJenis().getHargaSewa();
            
            ((DefaultTableModel) table.getModel()).addRow(rowData);
        }
        for (int a = 0; a < listp.size(); a++) {
            rowData[0] = listp.get(a).getIdPickUp();
            rowData[1] = listp.get(a).getJenis().getJenis();
            rowData[2] = listp.get(a).getNopol();
            rowData[3] = listp.get(a).getMerkPickUp();
            rowData[4] = listp.get(a).getWarnaPickUp();
            rowData[5] = listp.get(a).getNamaPickUp();
            rowData[6] = listp.get(a).getJenis().getHargaSewa();
            
            ((DefaultTableModel) table.getModel()).addRow(rowData);
        }
    }

    public void cari(String keyword) {
        String[] kolom = {"ID Mobil", "Jenis", "No Polisi", "Merk", "Warna", "Nama", "Harga Sewa / Hr"};
        ArrayList<MobilKeluarga> list = new MobilKeluarga().search(keyword);
        ArrayList<MobilPickUp> listp = new MobilPickUp().search(keyword);

        Object rowData[] = new Object[7];

        table.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (MobilKeluarga mk : list) {
            rowData[0] = mk.getIdMobil();
            rowData[1] = mk.getJenis().getJenis();
            rowData[2] = mk.getNopol();
            rowData[3] = mk.getMerkMobil();
            rowData[4] = mk.getWarnaMobil();
            rowData[5] = mk.getNamaMobil();
            rowData[6] = mk.getJenis().getHargaSewa();

            ((DefaultTableModel) table.getModel()).addRow(rowData);
        }
        for (MobilPickUp mp : listp) {
            rowData[0] = mp.getIdPickUp();
            rowData[1] = mp.getJenis().getJenis();
            rowData[2] = mp.getNopol();
            rowData[3] = mp.getMerkPickUp();
            rowData[4] = mp.getWarnaPickUp();
            rowData[5] = mp.getNamaPickUp();
            rowData[6] = mp.getJenis().getHargaSewa();

            ((DefaultTableModel) table.getModel()).addRow(rowData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidmobil = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        txtnopol = new javax.swing.JTextField();
        txtmerk = new javax.swing.JTextField();
        txtwarna = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        cmbView = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Mobil");

        jLabel2.setText("Jenis Mobil");

        jLabel3.setText("No Polisi");

        jLabel4.setText("Merk");

        jLabel5.setText("Warna");

        jLabel6.setText("Nama");

        txtidmobil.setEnabled(false);

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil Keluarga", "Mobil PickUp" }));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambah.setText("TAMBAH BARU");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("EXIT");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        cmbView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View All", "Mobil Keluarga", "Mobil PickUp" }));
        cmbView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViewActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidmobil)
                            .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnopol)
                            .addComponent(txtmerk)
                            .addComponent(txtwarna)
                            .addComponent(txtnama)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcari)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addComponent(cmbView, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (cmbJenis.getSelectedIndex() == 0) {
            MobilKeluarga mk = new MobilKeluarga();
            mk.setIdMobil(Integer.parseInt(txtidmobil.getText()));
            mk.setJenis((JenisMobil) cmbJenis.getSelectedItem());
            mk.setNopol(txtnopol.getText());
            mk.setMerkMobil(txtmerk.getText());
            mk.setWarnaMobil(txtwarna.getText());
            mk.setNamaMobil(txtnama.getText());
            mk.save();
            txtidmobil.setText(Integer.toString(mk.getIdMobil()));
            tampilkanData();
        } else {
            MobilPickUp mp = new MobilPickUp();
            mp.setIdPickUp(Integer.parseInt(txtidmobil.getText()));
            mp.setJenis((JenisMobil) cmbJenis.getSelectedItem());
            mp.setNopol(txtnopol.getText());
            mp.setMerkPickUp(txtmerk.getText());
            mp.setWarnaPickUp(txtwarna.getText());
            mp.setNamaPickUp(txtnama.getText());
            mp.save();
            txtidmobil.setText(Integer.toString(mp.getIdPickUp()));
            tampilkanData();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();

        if (row == 0) {
            MobilKeluarga mk = new MobilKeluarga().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
            mk.delete();
            kosongkanForm();
            tampilkanData();
        } else {
            MobilPickUp mp = new MobilPickUp().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
            mp.delete();
            kosongkanForm();
            tampilkanData();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();

        if (row == 0) {
            MobilKeluarga mk = new MobilKeluarga();
            mk = mk.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));

            txtidmobil.setText(String.valueOf(mk.getIdMobil()));
            cmbJenis.getModel().setSelectedItem(mk.getJenis().getJenis());
            txtnopol.setText(mk.getNopol());
            txtmerk.setText(mk.getMerkMobil());
            txtwarna.setText(mk.getWarnaMobil());
            txtnama.setText(mk.getNamaMobil());
        } else {
            MobilPickUp mp = new MobilPickUp();
            mp = mp.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));

            txtidmobil.setText(String.valueOf(mp.getIdPickUp()));
            cmbJenis.getModel().setSelectedItem(mp.getJenis().getJenis());
            txtnopol.setText(mp.getNopol());
            txtmerk.setText(mp.getMerkPickUp());
            txtwarna.setText(mp.getWarnaPickUp());
            txtnama.setText(mp.getNamaPickUp());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        cari(txtcari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void cmbViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViewActionPerformed
        // TODO add your handling code here:
        
         if (cmbView.getSelectedIndex() == 0) {
            tampilkanData();
        } else if (cmbView.getSelectedIndex() == 1) {
            String[] kolom = {"ID Mobil", "Jenis", "No Polisi", "Merk", "Warna", "Nama", "Harga Sewa / Hr"};
            ArrayList<MobilKeluarga> list = new MobilKeluarga().getAll();
            Object rowData[] = new Object[7];

            table.setModel(new DefaultTableModel(new Object[][]{}, kolom));

            for (int i = 0; i < list.size(); i++) {
                rowData[0] = list.get(i).getIdMobil();
                rowData[1] = list.get(i).getJenis().getJenis();
                rowData[2] = list.get(i).getNopol();
                rowData[3] = list.get(i).getMerkMobil();
                rowData[4] = list.get(i).getWarnaMobil();
                rowData[5] = list.get(i).getNamaMobil();
                rowData[6] = list.get(i).getJenis().getHargaSewa();

                ((DefaultTableModel) table.getModel()).addRow(rowData);
            }
        } else {
            String[] kolom = {"ID Mobil", "Jenis", "No Polisi", "Merk", "Warna", "Nama", "Harga Sewa / Hr"};
            ArrayList<MobilPickUp> listp = new MobilPickUp().getAll();
            Object rowData[] = new Object[7];

            table.setModel(new DefaultTableModel(new Object[][]{}, kolom));

            for (int a = 0; a < listp.size(); a++) {
                rowData[0] = listp.get(a).getIdPickUp();
                rowData[1] = listp.get(a).getJenis().getJenis();
                rowData[2] = listp.get(a).getNopol();
                rowData[3] = listp.get(a).getMerkPickUp();
                rowData[4] = listp.get(a).getWarnaPickUp();
                rowData[5] = listp.get(a).getNamaPickUp();
                rowData[6] = listp.get(a).getJenis().getHargaSewa();

                ((DefaultTableModel) table.getModel()).addRow(rowData);
            }
        }
    }//GEN-LAST:event_cmbViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidmobil;
    private javax.swing.JTextField txtmerk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnopol;
    private javax.swing.JTextField txtwarna;
    // End of variables declaration//GEN-END:variables

}
